name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:

env:
  IMAGE_NAME: "my-image"  # Nombre de tu imagen (cámbialo)

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write  # Necesario para push a Docker Hub

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Configuración de metadatos (tags, labels)
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ vars.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=tag

      # Autenticación en Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}  # Usa un token, no tu contraseña directa

      # Configuración de Buildx (para multi-arquitectura)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            image=moby/buildkit:master

      # Construcción y push de la imagen
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}  # Solo push en main
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64  # Opcional: multi-arquitectura
          cache-from: type=gha
          cache-to: type=gha,mode=max
