name: Docker CI with Dual Validation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Método 1: Validación con docker/build-push-action
      - name: Validate with docker/build
        uses: docker/build-push-action@v5
        with:
          context: .
          call: check  # Solo validación

      # Método 2: Validación con docker/bake-action
      - name: Validate with docker/bake
        uses: docker/bake-action@v4
        with:
          targets: validate-build

      # Build real solo si es push a main (opcional)
      - name: Build and push
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: tu-usuario/nombre-app:latest  # Reemplaza aquí